name: CI-CD Deployment

on:
  push:
    branches: [ "main" ] # Tự động chạy khi bạn push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}

            # Thực hiện các lệnh triển khai
            git pull origin main

            # Cài đặt PHP dependencies
            #composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            # Chạy migration (Quan trọng: dùng --force trên production)
            php artisan migrate --force

            # Nếu bạn muốn chạy seed (nên cân nhắc kỹ)
            # php artisan db:seed --force

            # Dọn dẹp và tối ưu cache
            #php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Cấp quyền lại cho storage/bootstrap/cache (nếu cần)
            #chmod -R 775 storage bootstrap/cache
